### ISSUE TITLE
Failed to notify Stash for commit ...

### ISSUE THREAD

**Issue by kuilee** [jenkinsci/stashnotifier-plugin#102]
Failed to notify Stash for commit 5508b46ead9c6f728564607af178933cd8c166e9 (<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /rest/build-status/1.0/commits/5508b46ead9c6f728564607af178933cd8c166e9 was not found on this server.</p>
</body></html>

**Comment by kuilee** [comment]
my stash notifier plugin version is 1.10.4

stash url:https://####/bitbucket
jenkins url:http://####:8080/

**Comment by scaytrase** [comment]
Could you confirm this url is (stashUrl + mentioned url) is accessible from your browser and from jenkins host (via wget or curl) ?

**Comment by kuilee** [comment]
@scaytrase  see upside, thank you.

**Comment by kuilee** [comment]
when i checked Ignore unverified SSL certificates, jenkins log:

Caught exception while notifying Stash with id 5508b46ead9c6f728564607af178933cd8c166e9
org.apache.http.conn.UnsupportedSchemeException: http protocol is not supported
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:108)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:388)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:636)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:251)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.prebuild(StashNotifier.java:194)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:816)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:811)
	at hudson.model.Build$BuildExecution.doRun(Build.java:142)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1750)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

**Comment by scaytrase** [comment]
I'll try to build an patched hpi soon with #77 changes which was closed accidentaly when reorganizing branches.

**Comment by kuilee** [comment]
Hi scaytrase, any update on this ? could you build a snapshot HPI for me ? thank you very much.

**Comment by scaytrase** [comment]
@kuilee Sorry for big delay, I've to work hard last days. I've prepared a patched hpi ontop of the latest 1.x branch and put it to #103. Please, check it.
