### ISSUE TITLE
Issue:  java.lang.NoSuchFieldError: INSTANCE

### ISSUE THREAD

**Issue by wdy0719** [jenkinsci/stashnotifier-plugin#104]
ERROR: Step ‘Notify Stash Instance’ aborted due to exception: 
java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.conn.HttpClientConnectionOperator.<init>(HttpClientConnectionOperator.java:74)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.<init>(BasicHttpClientConnectionManager.java:126)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.<init>(BasicHttpClientConnectionManager.java:143)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.getHttpClient(StashNotifier.java:370)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:634)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:251)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:208)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

**Comment by scaytrase** [comment]
We need a Jenkins version and the plugin version in order to investigate. Looks like dependency conflict which leads to different underlying http client api

**Comment by gonglancy** [comment]
hello, I also meet the same problems.  the Jenkins version is 1.651.3 and the stash notification plugin is 1.10.4.
