### ISSUE TITLE
error using the plugin in a pipeline script

### ISSUE THREAD

**Issue by sdmoralesma** [jenkinsci/stashnotifier-plugin#118]
my pipeline looks like:

```
    if ("$source" && "$destination") {
        step([$class: 'StashNotifier']) // Notifies the Stash Instance of an INPROGRESS build
    } else {
        error 'Undefined parameters, cannot build'
    }
```

but when the pipeline runs: 
```
java.lang.UnsupportedOperationException: no known implementation of interface jenkins.tasks.SimpleBuildStep is named StashNotifier
	at org.jenkinsci.plugins.structs.describable.DescribableModel.resolveClass(DescribableModel.java:417)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:371)
```

stashNotifier: v1.10.4
jenkins: v1.650

Ideas?

**Comment by scaytrase** [comment]
stashNotifier v1.10.4 does not support usage pipelines. Wait for next release, 1.11, I hope I do it soon

**Comment by sdmoralesma** [comment]
thank you for the release, that was faster than expected

**Comment by scaytrase** [comment]
@sdmoralesma please let us know is something goes wrong.
