### ISSUE TITLE
Connection timeout exception happening after upgrading to 1.11 from 1.10.4

### ISSUE THREAD

**Issue by ikari7789** [jenkinsci/stashnotifier-plugin#124]
I am no longer able to connect to our internal Bitbucket Server after upgrading to 1.11 from 1.10.4.
It just returns a connection timeout error.

```
Caught exception while notifying Stash with id 2681a1c8cfa592f0db029c433ff20d8a87a4a92c
org.apache.http.conn.ConnectTimeoutException: Connect to internal.bitbucket-server.com:443 [internal.bitbucket-server.com/X.X.X.X] failed: Connection timed out
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:149)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
    at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:688)
    at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:283)
    at org.jenkinsci.plugins.stashNotifier.StashNotifier.prebuild(StashNotifier.java:200)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:834)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:829)
    at hudson.model.Build$BuildExecution.doRun(Build.java:144)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1720)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:404)
Caused by: java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
    ... 21 more
```

Downgrading to 1.10.4, it seems to be working again.

**Comment by scaytrase** [comment]
Maybe some proxy configuration drops upon upgrading? Not sure how can the plugin cause timeout itself.

**Comment by ikari7789** [comment]
I think it would be due to the proxy, but I didn't change any proxy settings in Jenkins between upgrading. I'm not familiar very much with Java as of late, and especially not Jenkins plugin development, so I'm not sure where the bug may be.

**Comment by scaytrase** [comment]
Plugin has some own proxy settings. Verify that they migrate in a proper way. Tell me your Jenkins version also

**Comment by scaytrase** [comment]
There are also some changes in the latest release affecting the proxy configuration changes, but they are generally seems to be a refactoring

https://github.com/jenkinsci/stashnotifier-plugin/commit/f0d4c58c444d04253587dbc501a1640cb4199b34#diff-9905a5d95ec4490fc08dccacee897bc2L388

On a brief look I cannot find a real difference there, will take a more deep look later
