### ISSUE TITLE
Ignore unverified SSL certificates not working in 1.11.4

### ISSUE THREAD

**Issue by frami** [jenkinsci/stashnotifier-plugin#129]
After upgrading the plugin from 1.10.4 to 1.11.4 I got again the SSLHandshakeException. To solve this problem, I checked the "Ignore unverified SSL certificates" checkbox. But with 1.11.4 it doesn't work.

**Comment by scaytrase** [comment]
Does rolling back to 1.10.4 solves your problem?

**Comment by frami** [comment]
Yes, that solved the problem.

**Comment by scaytrase** [comment]
Can this be related with #124 ?

**Comment by frami** [comment]
I don't know. I tried it again with reconfiguration the plugin. But I got the same result.

```
Caught exception while notifying Stash with id 605c916e81924fa5743445effd1a767ce0051224
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:689)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:287)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.prebuild(StashNotifier.java:198)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:834)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:829)
	at hudson.model.Build$BuildExecution.doRun(Build.java:144)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 32 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 38 more
```

**Comment by scaytrase** [comment]
Looks different, thanks for the log

**Comment by tenerd** [comment]
Have same issue, workaround is to check 'ignoreUnverifiedSSLPeer' in all jobs.

eg config xml is:

```
<org.jenkinsci.plugins.stashNotifier.StashNotifier plugin="stashNotifier@1.11.4">
      <stashServerBaseUrl></stashServerBaseUrl>
      <credentialsId></credentialsId>
      <ignoreUnverifiedSSLPeer>true</ignoreUnverifiedSSLPeer>
      <commitSha1></commitSha1>
      <includeBuildNumberInKey>false</includeBuildNumberInKey>
      <projectKey></projectKey>
      <prependParentProjectKey>false</prependParentProjectKey>
      <disableInprogressNotification>false</disableInprogressNotification>
      <globalConfig>
        <adminAddress>..</adminAddress>
        <adminAddress>..</adminAddress>
        <jenkinsUrl>..</jenkinsUrl>
      </globalConfig>
```
Default is with
`      <ignoreUnverifiedSSLPeer>false</ignoreUnverifiedSSLPeer>`

**Comment by scaytrase** [comment]
Does only manual global config edit helps or global GUI config works too?

**Comment by Tetradeus** [comment]
What's the difference between both global config ?
From what I tested, the checkbox in global config is ignored, but the one in the job config works. It would be great if the global config was enough.

**Comment by scaytrase** [comment]
https://github.com/jenkinsci/stashnotifier-plugin/blob/release/1.x/src/main/java/org/jenkinsci/plugins/stashNotifier/StashNotifier.java#L398

Checkboxes should work with `OR`

**Comment by scaytrase** [comment]
Try if https://github.com/jenkinsci/stashnotifier-plugin/pull/185 has fixed this
