### ISSUE TITLE
ERROR: Step ‘Notify Stash Instance’ aborted due to exception

### ISSUE THREAD

**Issue by gonglancy** [jenkinsci/stashnotifier-plugin#161]
These days I use the Stash Notifier plugin, I meet below errors:

ERROR: Step ‘Notify Stash Instance’ aborted due to exception: 
java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.impl.conn.HttpClientConnectionOperator.<init>(HttpClientConnectionOperator.java:74)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.<init>(BasicHttpClientConnectionManager.java:126)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.<init>(BasicHttpClientConnectionManager.java:143)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.getHttpClient(StashNotifier.java:372)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:636)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:251)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:206)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE

My Jenkins version is 1.651.3 and plugin version is 1.10.4. This plugin can work well before. And I do not update the Jenkins version or the plugin version meanwhile

**Comment by gonglancy** [comment]
@scaytrase Do you have any idea?

**Comment by scaytrase** [comment]
@gonglancy Not yet. Google says that it could be dependency issue, but I cannot be sure, that we can do something about it for outdated versions without updating.

**Comment by gonglancy** [comment]
@scaytrase  Thank you for you feedback.
Do you have any suggestions what shall I do to avoid this issue? I have update the plugin, but the error still occurs. 
My another Jenkins can work well with this plugin.  I can't find the root cause

**Comment by scaytrase** [comment]
Another jenkins has the same version?

**Comment by gonglancy** [comment]
Another jenkins can work well, but I can't find the difference, all my jenkins are setup in Windows

**Comment by scaytrase** [comment]
You can compare `/systemInfo` pages to find differences

**Comment by gonglancy** [comment]
@scaytrase I found the root cause, it is because my plugin **git**, **credentials**,  **git client** is too old, I have updated these plugins, then the functions can work again.

**Comment by scaytrase** [comment]
@gonglancy glad to hear that you solver your problem
