### ISSUE TITLE
Notifying Stash at "null"

### ISSUE THREAD

**Issue by qianmuxi** [jenkinsci/stashnotifier-plugin#197]
Notifying Stash at "null"
Caught exception while notifying Stash with id 20b2727e8e2283bc03db52180a7c27dff0ab38d0
java.net.MalformedURLException
	at java.net.URL.<init>(URL.java:627)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.getHttpClient(StashNotifier.java:426)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:746)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:326)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:277)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:244)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException

**Comment by scaytrase** [comment]
Hi, @qianmuxi. Can you please share your configuration sample? Looks like you've enabled the plugin, but didn't configure the server URL

**Comment by qianmuxi** [comment]
@scaytrase my configuration like this
def notifyBitbucket(String state) {

    if('SUCCESS' == state || 'FAILED' == state) {
        currentBuild.result = state         // Set result of currentBuild !Important!
    }
    notifyBitbucket commitSha1: '${sourceCommitHash}', 
                credentialsId: '', 
                disableInprogressNotification: false, 
                considerUnstableAsSuccess: true, 
                ignoreUnverifiedSSLPeer: true, 
                includeBuildNumberInKey: false, 
                prependParentProjectKey: false, 
                projectKey: '', 
                stashServerBaseUrl: 'my company stash site'

}

**Comment by scaytrase** [comment]
Looks legit. Could you please provide also Jenkins and plugin version?

**Comment by qianmuxi** [comment]
my local jenkins  is Jenkins ver. 2.125, and stashnotifier-plugin is release/1.x.

**Comment by scaytrase** [comment]
`release/1.x` is not a proper version for plugin, one could be located on jenkins installed plugins page
