### ISSUE TITLE
java.lang.ClassCastException: expects class java.lang.String

### ISSUE THREAD

**Issue by SDedik** [jenkinsci/stashnotifier-plugin#266]
Using `Bitbucket Server Notifier` plugin version '1.20'
Jenkins version is '2.249.2'

This is literally how plugin is invoked from Jenkins pipeline:
```
notifyBitbucket(buildStatus: 'FAILED')
```
In the Jenkins log exception is logged on every plugin invocation (trimmed for brevity):
```
Oct 26, 2020 2:57:01 AM WARNING org.jenkinsci.plugins.structs.describable.DescribableModel uninstantiate2
Cannot create control version of class org.jenkinsci.plugins.workflow.steps.CoreStep using {delegate=@notifyBitbucket$StashNotifier(buildStatus=FAILED,considerUnstableAsSuccess=false,disableInprogressNotification=false,ignoreUnverifiedSSLPeer=false,includeBuildNumberInKey=false,prependParentProjectKey=false)}
java.lang.ClassCastException: org.jenkinsci.plugins.stashNotifier.StashNotifier.buildStatus expects class java.lang.String but received class org.jenkinsci.plugins.stashNotifier.StashBuildState
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:492)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)
Caused: java.lang.IllegalArgumentException: Could not instantiate {buildStatus=FAILED, considerUnstableAsSuccess=false, disableInprogressNotification=false, ignoreUnverifiedSSLPeer=false, includeBuildNumberInKey=false, prependParentProjectKey=false} for org.jenkinsci.plugins.stashNotifier.StashNotifier
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
	at org.jenkinsci.plugins.structs.describable.UninstantiatedDescribable.instantiate(UninstantiatedDescribable.java:208)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:466)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)
Caused: java.lang.IllegalArgumentException: Could not instantiate {delegate=@notifyBitbucket$StashNotifier(buildStatus=FAILED,considerUnstableAsSuccess=false,disableInprogressNotification=false,ignoreUnverifiedSSLPeer=false,includeBuildNumberInKey=false,prependParentProjectKey=false)} for org.jenkinsci.plugins.workflow.steps.CoreStep
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.uninstantiate2(DescribableModel.java:672)
	at org.jenkinsci.plugins.workflow.actions.ArgumentsAction.resolve(ArgumentsAction.java:306)
...
```
The notification is successfully sent to bitbucket, but those exceptions litter Jenkins log making it harder to monitor for real issues.

**Comment by hcbraun** [comment]
I get the same exceptions unfortunately with notification **not** working

**Comment by scaytrase** [comment]
Was it working before any kinds of updates? Last release was like a year ago and introduced build status override by @westarne https://github.com/jenkinsci/stashnotifier-plugin/pull/243

**Comment by hcbraun** [comment]
No, this is a new installation.
Bitbucket Server Notifier plugin version '1.20'
Jenkins version is '2.249.3'
Atlassian Bitbucket v7.7.1

**Comment by hcbraun** [comment]
This version throws the String cast exception:
```
try {
  ...
  notifyBitbucket(buildStatus: 'SUCCESS', buildName: some_name)
} catch (Exception e) {
  notifyBitbucket(buildStatus: 'FAILED', buildName: some_name)
}
```

This works without exceptions:
```
try {
  ...
  currentBuild.result = 'SUCCESS'
} catch (Exception e) {
  currentBuild.result = 'FAILED'
}   
notifyBitbucket(buildName: some_name)
```

Maybe this is related: 
I have Jenkins building PRs with the repository setting:
Discover pull requests from origin, Strategy: Merge the pull request with the current target branch

The plugin is doing 3 notifications on each call for 3 different commit id's. The first two commit id's are the temporary ones generated by Jenkins during the merge. Only the last commit id is valid and known by the Bitbucket server:
```
Notifying Bitbucket at "https://..."
Notified Bitbucket for commit with id a5...
Notifying Bitbucket at "https://..."
Notified Bitbucket for commit with id 9e...
Notifying Bitbucket at "https://..."
Notified Bitbucket for commit with id d5...
```

**Comment by fcristovao** [comment]
I'm seeing the same problem:

```
Jan 26, 2021 11:56:46 AM WARNING org.jenkinsci.plugins.structs.describable.DescribableModel uninstantiate2
Cannot create control version of class org.jenkinsci.plugins.workflow.steps.CoreStep using {delegate=@notifyBitbucket$StashNotifier(buildName=<redacted>,buildStatus=INPROGRESS,commitSha1=<redacted>,considerUnstableAsSuccess=false,disableInprogressNotification=false,ignoreUnverifiedSSLPeer=false,includeBuildNumberInKey=false,prependParentProjectKey=false,projectKey=<redacted>)}
java.lang.ClassCastException: org.jenkinsci.plugins.stashNotifier.StashNotifier.buildStatus expects class java.lang.String but received class org.jenkinsci.plugins.stashNotifier.StashBuildState
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:492)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)
Caused: java.lang.IllegalArgumentException: Could not instantiate {buildName=<redacted>, buildStatus=INPROGRESS, commitSha1=<redacted>, considerUnstableAsSuccess=false, disableInprogressNotification=false, ignoreUnverifiedSSLPeer=false, includeBuildNumberInKey=false, prependParentProjectKey=false, projectKey=<redacted>} for org.jenkinsci.plugins.stashNotifier.StashNotifier
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
	at org.jenkinsci.plugins.structs.describable.UninstantiatedDescribable.instantiate(UninstantiatedDescribable.java:208)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:466)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)
Caused: java.lang.IllegalArgumentException: Could not instantiate {delegate=@notifyBitbucket$StashNotifier(buildName=<redacted>,buildStatus=INPROGRESS,commitSha1=<redacted>,considerUnstableAsSuccess=false,disableInprogressNotification=false,ignoreUnverifiedSSLPeer=false,includeBuildNumberInKey=false,prependParentProjectKey=false,projectKey=kred)} for org.jenkinsci.plugins.workflow.steps.CoreStep
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.uninstantiate2(DescribableModel.java:672)
	at org.jenkinsci.plugins.workflow.actions.ArgumentsAction.resolve(ArgumentsAction.java:306)
	at org.jenkinsci.plugins.workflow.actions.ArgumentsAction.getResolvedArguments(ArgumentsAction.java:293)
...
```

Bitbucket Server Notifier plugin version '1.20'
Jenkins version is '2.263.1'

**Comment by pashcan** [comment]
Still seeing this (or similar error) with Jenkins 2.319.1 & the most recent stashNotifier version 1.25.
```
WARNING org.jenkinsci.plugins.structs.describable.DescribableModel uninstantiate2
Cannot create control version of class org.jenkinsci.plugins.workflow.steps.CoreStep using {delegate=@notifyBitbucket$StashNotifier(buildStatus=SUCCESSFUL)}
java.lang.ClassCastException: class org.jenkinsci.plugins.stashNotifier.StashNotifier.setBuildStatus() expects class java.lang.String but received class org.jenkinsci.plugins.stashNotifier.StashBuildState
...
```
Does not appear to be an issue with just using `notifyBitbucket()` call without any parameters but definitely occurs with `notifyBitbucket(buildStatus: 'SUCCESSFUL')`. 
Unfortunately, the logs are spammed even when none of the jobs that have those calls are running.

**Comment by duckaraptor** [comment]
I am also facing the same issue. 
Jenkins verison:  2.319.1
stashNotifier version: 1.25

Throws warning logs when using `notifyBitbucket(buildStatus: 'INPROGRESS')`

```
Cannot create control version of class org.jenkinsci.plugins.workflow.steps.CoreStep using {delegate=@notifyBitbucket$StashNotifier(buildStatus=FAILED,considerUnstableAsSuccess=false,disableInprogressNotification=false,ignoreUnverifiedSSLPeer=false,includeBuildNumberInKey=false,prependParentProjectKey=false)}
java.lang.ClassCastException: org.jenkinsci.plugins.stashNotifier.StashNotifier.buildStatus expects class java.lang.String but received class org.jenkinsci.plugins.stashNotifier.StashBuildState
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:492)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)
Caused: java.lang.IllegalArgumentException: Could not instantiate {buildStatus=FAILED, considerUnstableAsSuccess=false, disableInprogressNotification=false, ignoreUnverifiedSSLPeer=false, includeBuildNumberInKey=false, prependParentProjectKey=false} for org.jenkinsci.plugins.stashNotifier.StashNotifier
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
	at org.jenkinsci.plugins.structs.describable.UninstantiatedDescribable.instantiate(UninstantiatedDescribable.java:208)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:466)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)
Caused: java.lang.IllegalArgumentException: Could not instantiate 
```

**Comment by scaytrase** [comment]
@westarne may be you know, should [this one](https://github.com/jenkinsci/stashnotifier-plugin/pull/246/files#diff-fb4c40304487deae335fc3493d7fedd0b8421a3338020271b6fa59003920ccaaR254) be `@DataBoundSetter` too maybe? Looks loke overloading goes wrong here

**Comment by westarne** [comment]
Could this be the declarative pipeline again? In our setup with the scripted pipeline this exact command `notifyBitbucket(buildStatus: 'INPROGRESS')` is working fine. 

I think i remember having tested it with the `@DataBoundSetter` on the not string method and it did not work in the scripted pipeline. And I'm pretty certain it can only be used once per property. Maybe it actually has to be an Object setter to split the logic in one method for both types...

**Comment by westarne** [comment]
I could try to implement that, not sure when I'll get to it.

As far as I understood the comments, the issue is the same as before, so the last PR didn't break anything, it just did not solve it? Or is that actually something breaking only in the latest version? (1.25 not in earlier versions)

**Comment by scaytrase** [comment]
https://issues.jenkins.io/browse/JENKINS-64637
