### ISSUE TITLE
UnsupportedSchemeException: http protocol is not supported while notifying Stash

### ISSUE THREAD

**Issue by mpkusnierz** [jenkinsci/stashnotifier-plugin#57]
I am getting this exception with v1.8 of the Stash Notifier plugin. But it impacts some jobs and not others, currently unable to work out what is different about the jobs to cause this problem. 
The Repository URL is http://stash-my-server:port/scm/repo/my-project.git
The Repository browser is set to stash, with an equivalent URL: http://stash-my-server:port/projects/repo/repos/my-project/browse
The Notify Stash Instance section has got the Stash base URL set to blank; but this works for other jobs using the same jenkins server and stash instance.

Caught exception while notifying Stash with id {HASH}
org.apache.http.conn.UnsupportedSchemeException: http protocol is not supported
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:108)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:388)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:556)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:207)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.prebuild(StashNotifier.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:816)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:811)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:664)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
	at hudson.model.Run.execute(Run.java:1751)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

**Comment by cClaude** [comment]
Having the same issue. Fix the issues by removing an other plug-in : ssh-agent

**Comment by marufaytekin** [comment]
When we downgrade to 1.7 we are getting following error:

Failed to notify Stash for commit 5c458cc3866a7ebacceec1f28770899c6b637a81 (<HEAD><TITLE>internal error - server connection terminated</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>internal error - server connection terminated</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
Description: internal error - server connection terminated</B></FONT>
<HR>

</BODY>
)

Stash Base URL http://git.mkk.com.tr:7990

Any idea  why am I getting this error?

**Comment by scaytrase** [comment]
Have you re-checked your configuration after downgrading?

**Comment by marufaytekin** [comment]
My issue s resolved. You can see the details in #69

**Comment by eratolekov** [comment]
In my case this exception was raised after I set proxy settings in Jenkins web-interface.
Stash available over https, Jenkins trying to connect to Stash via proxy over https and exception is raised.

**Comment by scaytrase** [comment]
Is your scheme is like

Jenkins <-https-> Proxy <-http-> Stash

?

**Comment by eratolekov** [comment]
@scaytrase 
Jenkins -> proxy:3128 -> Stash:443

**Comment by scaytrase** [comment]
@eratolekov does you issue still exists and could you confirm that #77 PR fix it (I can build a snapshot HPI for you if you need)

**Comment by kuilee** [comment]
Hi, I have this issue too, could you build a snapshot HPI for me ? Thank you very much.

**Comment by gruetter** [comment]
Had the same problem. My problem was resolved by adding the Bitbucket server to the _No Proxy Host_ list in Jenkins.

**Comment by Kib1967** [comment]
@scaytrase, I applied PR #77 as a patch to 1.10.4 for my use case, which is exactly the same as that described by @eratolekov, and built a snapshot HPI. It resolved my problem. Please consider merging #77 for the next release.

**Comment by scaytrase** [comment]
Merged #77 via #103 for next release
