### ISSUE TITLE
Build with no revision to build causes NullPointerException

### ISSUE THREAD

**Issue by danielksan81** [jenkinsci/stashnotifier-plugin#66]
Hi,
If I have a build configured with currently no active branch causes the StashNotifier plugin to throw a NullPointerException:
Seen branch in repository origin/master
Seen 1 remote branch
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Sending e-mails to: *************
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.lookupCommitSha1s(StashNotifier.java:263)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:204)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:171)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Build step 'Notify Stash Instance' marked build as failure
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE

**Comment by scaytrase** [comment]
@danielksan81 I hope it is resolved with #58 now

@gruetter btw, do we have any source of SNAPSHOT builds to give them for testing purposes?

**Comment by danielksan81** [comment]
A snapshot build would be nice, then I would like to test it.

**Comment by scaytrase** [comment]
@danielksan81 I've setup a travis builds on my fork. You can grab a snapshot built plugin package from release page

https://github.com/scaytrase/stashnotifier-plugin/releases
