### ISSUE TITLE
NullPointerException in StashNotifier.lookupCommitSha1s

### ISSUE THREAD

**Issue by juherr** [jenkinsci/stashnotifier-plugin#70]
Plugin version: 1.8
Jenkins version: 1.627
Stash version: 3.11.2

```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.lookupCommitSha1s(StashNotifier.java:263)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:204)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:171)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Build step 'Notify Stash Instance' marked build as failure
```

**Comment by scaytrase** [comment]
@juherr Could you try if snapshout build from [releases page](https://github.com/jenkinsci/stashnotifier-plugin/releases) solves this problem? I hope that was fixed in #58 

It contains some backward incompatible enchantments (it uses credential plugin instead of plain login-pass), so It will require reconfiguration on upgrade and downgrade.

**Comment by juherr** [comment]
No more NPE with 1.9-alpha1

**Comment by scaytrase** [comment]
Thanks for testing @juherr :+1:
