### ISSUE TITLE
NullPointerException if no Stash user password is specified

### ISSUE THREAD

**Issue by aWildElephant** [jenkinsci/stashnotifier-plugin#71]
I get a NullPointerException if I leave the Stash user password field blank in the post-build action.

Caught exception while notifying Stash with id f213d5f5d67ac56580b2071d0e1088788f5897c2
java.lang.NullPointerException
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.createRequest(StashNotifier.java:591)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.notifyStash(StashNotifier.java:553)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.processJenkinsEvent(StashNotifier.java:207)
	at org.jenkinsci.plugins.stashNotifier.StashNotifier.perform(StashNotifier.java:174)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1053)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:537)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)

Note that if I fill it the build hangs for several minutes. Stash notifiers end up by failing with a java.net.SocketException: "Connection reset".

I am using Jenkins v1.627, StashNotifier v1.8 and Stash v3.10.

**Comment by scaytrase** [comment]
Is password set on global level?

**Comment by scaytrase** [comment]
Anyway, this concrete proplem should gone with latest snapshot version, as we switched to credentials at #62. I should check if empty credentials will fail the notification process with exception

**Comment by aWildElephant** [comment]
Thanks for your answer, glad I'll be able to use credentials soon.
